---
title: "Publications"
title-block-banner: true
page-layout: full
---

Here's a list of publications that have resulted from my research. You can follow this work on [Google Scholar](https://scholar.google.com/citations?user=CRU3WVMAAAAJ&hl=en) and [ResearchGate](https://www.researchgate.net/profile/Jeff-Baldock). If you encounter a paywall, please email me and I will be happy to send you a copy of the paper.


## In Review

- **Baldock JR**, Fair JBH, Letcher BH, Al-Chokhachy R, Dunham JB, & Muhlfeld CC. Headwater streamflow variability is amplified by drought. *In review* at *Nature Water*.

- **Baldock JR**, Rosenthal WC, Campbell MR, Wagner CE, Al-Chokhachy R, & Walters A. Riverscape heterogeneity shapes population diversity for a migratory fish. *In review* at *Ecological Applications*.

## Accepted

- **Baldock JR**, Al-Chokhachy R, & Walters A. *In press*. Groundwater structures fish growth and production across a riverscape. *Freshwater Biology*. (publication delayed due to 2025 government shutdown)

## 2024

- **Baldock JR**. 2024. Biocomplexity of Yellowstone Cutthroat Trout: from Individuals to Metapopulations. *PhD Dissertation*, University of Wyoming. 

## 2023

- **Baldock JR**, Al-Chokhachy R, Campbell MR, & Walters A. 2023. Timing of reproduction underlies fitness trade-offs for a salmonid fish. *Oikos* e10184. DOI: [10.1111/oik.10184](https://doi.org/10.1111/oik.10184)

- **Baldock JR**, Al-Chokhachy R, Walsworth TE, & Walters. 2023. Redd superimposition mediates the accuracy, precision, and significance of redd counts for cutthroat trout. *Canadian Journal of Aquatic and Fishery Sciences* 80(5):825-839. DOI: [10.1139/cjfas-2022-0267](https://doi.org/10.1139/cjfas-2022-0267)

## 2020

- Walsworth TE, **Baldock JR**, Schindler DE & Zimmerman CE. 2020. Interaction between watershed features and climate forcing affects habitat profitability for juvenile salmonids. *Ecosphere* 11(10): e03266. DOI: [10.1002/ecs2.3266](https://doi.org/10.1002/ecs2.3266)

## 2016

- **Baldock JR**, Armstrong JB, Schindler DE, & Carter JL. 2016. Juvenile coho salmon track a seasonally shifting thermal mosaic across a river floodplain. *Freshwater Biology* 61(9):1454-1465. DOI: [10.1111/fwb.12784](https://doi.org/10.1111/fwb.12784)
